name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Checks
    runs-on: ubuntu-24.04

    defaults:
      run:
        workflow_directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@8.1.0
          with:
            enable-cache: true

      - name: Run Backend Formatter check
        run: uv run --frozen ruff format --check .

      - name: Run Backend linter check
        run: uv run --frozen ruff check .

      - name: Run backend tests
        run: uv run --frozen pytest
    
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-24.04

    defaults:
      run:
        workflow_directory: frontend

      steps:
        - name: Checkout repository
          uses: actions/checkout@v6

        - name: Set up Node.js
          uses: actions/setup-node@v6
          with:
            node-version: 24
            cache: npm
            cache-dependency-path: frontent/package-lock.json

        - name: Install frontend dependencies
          run: npm ci
        
        - name: Run frontend linter
          run: npm run lint

        - name: Build frontend
          run: npm run build